### ISSUE TITLE
Export themes as auto-generated XPIs

### ISSUE THREAD

**Issue by jaredhirsch** [6a68/easythemes#8]
Allow themes to be exported as XPIs.

This is a bit further out, so not breaking into component issues just yet.
- [ ] Provide a separate 'sharing' form where the user can fill out the standard add-on manifest fields
- [ ] Template JSON values into a boilerplate `bootstrap.js` file that loads the JSON into the `'extensions.easythemes.value'` preference
- [ ] Zip up the `bootstrap.js` file and export as an XPI
- [ ] Integrate with addons.mozilla.org: start with a 'sign in to share your theme' call to action
